{{- range .Values.targets }}
{{- if and .dsn (not .existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysqlpulse.targetFullname" (dict "root" $ "target" .) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mysqlpulse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
type: Opaque
stringData:
  dsn: {{ .dsn | quote }}
  {{- if .telegramToken }}
  telegram-token: {{ .telegramToken | quote }}
  {{- end }}
  {{- if .grafanaToken }}
  grafana-token: {{ .grafanaToken | quote }}
  {{- end }}
{{- end }}
{{- end }}
