{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-mysqlpulse
  labels:
    app.kubernetes.io/name: mysqlpulse
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysqlpulse
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
