apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysqlpulse
  labels:
    app.kubernetes.io/name: mysqlpulse
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: mysqlpulse
    app.kubernetes.io/instance: {{ .Release.Name }}
